# Generated by Django 4.2.5 on 2023-12-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0005_emailaddress_idx_upper_email'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
