# Generated by Django 4.2.5 on 2023-12-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0005_alter_comentario_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
