# Generated by Django 4.2.5 on 2023-12-10 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0007_alter_comentario_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receita.categoria'),
        ),
    ]
